### NISHANTH IRUTHAYARAJ
Matric. No: 1522044


**Data Preprocessing**

In [1]:
import pandas as pd
import numpy as np

#Reading files and Correcting Timestamp#
c_heads = ['Time', 'Device', 'e1' , 'e2' , 'e3' , 'e4' , 'e5' , 'e6' ,'Label']
df_sub1_esense = pd.read_csv('eSense_sbj1.csv', names = c_heads)
df_sub1_esense['Time'] = pd.to_datetime(df_sub1_esense['Time'], unit = 'ms') + pd.Timedelta('02:00:00')
df_sub1_esense = df_sub1_esense.set_index('Time').resample('10L', offset = 4000000).first().interpolate()
df_sub1_esense = df_sub1_esense.sort_index()

df_sub2_esense = pd.read_csv('eSense_sbj2.csv', names = c_heads)
df_sub2_esense['Time'] = pd.to_datetime(df_sub2_esense['Time'], unit = 'ms') + pd.Timedelta('02:00:00')
df_sub2_esense = df_sub2_esense.set_index('Time').resample('10L', offset = 4000000).first().interpolate()
df_sub2_esense = df_sub2_esense.sort_index()

In [2]:
#Data Interpolating and Upsampling
#Subject 1 ankle
df_layup1_ankle = pd.read_csv('layup_sbj1_ankle.csv', index_col = 0, comment= ';')
df_layup1_ankle.index = pd.date_range(start = '2021-04-14 18:22:13.554', periods = df_layup1_ankle.shape[0], freq = "10.869565L")
df_layup1_ankle = df_layup1_ankle.resample('10L', offset = 4000000).first().interpolate()

df_movements1_ankle_1 = pd.read_csv('movements_sbj1_ankle_1.csv', index_col = 0, comment= ';')
df_movements1_ankle_1.index = pd.date_range(start = '2021-04-14 18:42:32.024', periods = df_movements1_ankle_1.shape[0], freq = "10.869565L")
df_movements1_ankle_1 = df_movements1_ankle_1.resample('10L', offset = 4000000).first().interpolate()

df_shooting1_ankle_1 = pd.read_csv('shooting_sbj1_ankle.csv', index_col = 0, comment= ';')
df_shooting1_ankle_1.index = pd.date_range(start = '2021-04-14 18:12:54.024', periods = df_shooting1_ankle_1.shape[0], freq = "10.869565L")
df_shooting1_ankle_1 = df_shooting1_ankle_1.resample('10L', offset = 4000000).first().interpolate()

df_sub1_ankle = pd.concat([df_layup1_ankle,df_movements1_ankle_1,df_shooting1_ankle_1])
df_sub1_ankle = df_sub1_ankle.set_axis(['a1', 'a2', 'a3'], axis = 'columns')
#df_sub1_ankle = df_sub1_ankle.sort_index()

#Subject 2 ankle
df_dribbling2_ankle = pd.read_csv('dribbling_sbj2_ankle.csv', index_col = 0, comment= ';')
df_dribbling2_ankle.index = pd.date_range(start = '2021-04-14 19:26:42.914', periods = df_dribbling2_ankle.shape[0], freq = "10.869565L")
df_dribbling2_ankle = df_dribbling2_ankle.resample('10L', offset = 4000000).first().interpolate()

df_layup2_ankle = pd.read_csv('layup_sbj2_ankle.csv', index_col = 0, comment= ';')
df_layup2_ankle.index = pd.date_range(start = '2021-04-14 19:16:25.794', periods = df_layup2_ankle.shape[0], freq = "10.869565L")
df_layup2_ankle = df_layup2_ankle.resample('10L', offset = 4000000).first().interpolate()

df_movements2_ankle_1 = pd.read_csv('movements_sbj2_ankle_1.csv', index_col = 0, comment= ';') 
df_movements2_ankle_1.index = pd.date_range(start = '2021-04-14 19:36:19.244', periods = df_movements2_ankle_1.shape[0], freq = "10.869565L")
df_movements2_ankle_1 = df_movements2_ankle_1.resample('10L', offset = 4000000).first().interpolate()

df_shooting2_ankle_1 = pd.read_csv('shooting_sbj2_ankle_1.csv', index_col = 0, comment= ';')
df_shooting2_ankle_1.index = pd.date_range(start = '2021-04-14 18:55:50.364', periods = df_shooting2_ankle_1.shape[0], freq = "10.869565L")
df_shooting2_ankle_1 = df_shooting2_ankle_1.resample('10L', offset = 4000000).first().interpolate()

df_sub2_ankle = pd.concat([df_dribbling2_ankle, df_layup2_ankle, df_movements2_ankle_1, df_shooting2_ankle_1])
df_sub2_ankle = df_sub2_ankle.set_axis(['a1','a2','a3'], axis = 'columns')
#df_sub2_ankle = df_sub2_ankle.sort_index()

In [3]:
#Subject 1 wrist
df_layup1_wrist = pd.read_csv('layup_sbj1_wrist.csv', index_col = 0, comment= ';')
df_layup1_wrist.index = pd.date_range(start = '2021-04-14 18:22:52.524', periods = df_layup1_wrist.shape[0], freq = "10.869565L")
df_layup1_wrist = df_layup1_wrist.resample('10L', offset = 4000000).first().interpolate()

df_movements1_wrist = pd.read_csv('movements_sbj1_wrist.csv', index_col = 0, comment= ';')
df_movements1_wrist.index = pd.date_range(start = '2021-04-14 18:42:05.244', periods = df_movements1_wrist.shape[0], freq = "10.869565L")
df_movements1_wrist = df_movements1_wrist.resample('10L', offset = 4000000).first().interpolate()

df_shooting1_wrist = pd.read_csv('shooting_sbj1_wrist.csv', index_col = 0, comment= ';')
df_shooting1_wrist.index = pd.date_range(start = '2021-04-14 18:13:12.834', periods = df_shooting1_wrist.shape[0], freq = "10.869565L")
df_shooting1_wrist = df_shooting1_wrist.resample('10L', offset = 4000000).first().interpolate()

df_sub1_wrist = pd.concat([df_layup1_wrist, df_movements1_wrist, df_shooting1_wrist])
df_sub1_wrist = df_sub1_wrist.set_axis(['w1','w2','w3'], axis = 'columns')
#df_sub1_wrist = df_sub1_wrist.sort_index()

#Subject 2 wrist
df_dribbling2_wrist = pd.read_csv('dribbling_sbj2_wrist.csv', index_col = 0, comment= ';')
df_dribbling2_wrist.index = pd.date_range(start = '2021-04-14 19:26:24.464', periods = df_dribbling2_wrist.shape[0], freq = "10.869565L")
df_dribbling2_wrist = df_dribbling2_wrist.resample('10L',  offset = 4000000).first().interpolate()

df_layup2_wrist = pd.read_csv('layup_sbj2_wrist.csv', index_col = 0, comment= ';')
df_layup2_wrist.index = pd.date_range(start = '2021-04-14 19:16:05.604', periods = df_layup2_wrist.shape[0], freq = "10.869565L")
df_layup2_wrist = df_layup2_wrist.resample('10L',  offset = 4000000).first().interpolate()

df_movements2_wrist = pd.read_csv('movements_sbj2_wrist.csv', index_col = 0, comment= ';') 
df_movements2_wrist.index = pd.date_range(start = '2021-04-14 19:36:45.074', periods = df_movements2_wrist.shape[0], freq = "10.869565L")
df_movements2_wrist = df_movements2_wrist.resample('10L',  offset = 4000000).first().interpolate()

df_shooting2_wrist = pd.read_csv('shooting_sbj2_wrist.csv', index_col = 0, comment= ';')
df_shooting2_wrist.index = pd.date_range(start = '2021-04-14 18:56:21.474', periods = df_shooting2_wrist.shape[0], freq = "10.869565L")
df_shooting2_wrist = df_shooting2_wrist.resample('10L',  offset = 4000000).first().interpolate()

df_sub2_wrist = pd.concat([df_dribbling2_wrist, df_layup2_wrist, df_movements2_wrist, df_shooting2_wrist])
df_sub2_wrist = df_sub2_wrist.set_axis(['w1','w2','w3'], axis = 'columns')
#df_sub2_wrist = df_sub2_wrist.sort_index()

In [4]:
#Merging and Normalising each 
df_sub1 = df_sub1_esense.merge(df_sub1_ankle, left_index=True, right_index=True)
df_1 = df_sub1.merge(df_sub1_wrist, left_index=True, right_index=True)
df_1 = (df_1 - df_1.mean()) / df_1.std()
df_1 = df_1.drop(['Device'], axis = 1)

df_sub2 = df_sub2_esense.merge(df_sub2_ankle, left_index=True, right_index=True)
df_2 = df_sub2.merge(df_sub2_wrist, left_index=True, right_index=True)
df_2 = (df_2 - df_2.mean()) / df_2.std()
df_2 = df_2.drop(['Device'], axis = 1)

In [5]:
#Finding Samples for Time Intersection
intersection_1 = [df_1.index.isin(df_1.between_time('18:23:14', '18:25:28').index),
                  df_1.index.isin(df_1.between_time('18:45:17', '18:47:16').index),
                  df_1.index.isin(df_1.between_time('18:13:25', '18:15:47').index),
                  df_1.index.isin(df_1.between_time('18:42:48', '18:45:17').index)]
activity_1 = ['layup', 'running', 'shooting', 'walking']
df_1['Label'] = np.select(intersection_1, activity_1, 'Null')
df_1['Subjects'] = 'Subject1'
df_1 = df_1[['e1','e2','e3','e4','e5','e6','a1','a2','a3','w1','w2','w3','Label','Subjects']]

intersection_2 = [df_2.index.isin(df_2.between_time('19:26:58', '19:29:59').index), 
                  df_2.index.isin(df_2.between_time('19:17:35', '19:20:14').index),
                  df_2.index.isin(df_2.between_time('19:39:47', '19:41:55').index),
                  df_2.index.isin(df_2.between_time('19:00:14', '19:02:12').index),
                  df_2.index.isin(df_2.between_time('19:37:15', '19:39:46').index)]
activity_2 = ['dribbling', 'layup', 'running', 'shooting', 'walking']
df_2['Label'] = np.select(intersection_2, activity_2, 'Null')
df_2['Subjects'] = 'Subject2'
df_2 = df_2[['e1','e2','e3','e4','e5','e6','a1','a2','a3','w1','w2','w3','Label','Subjects']]

df = pd.concat([df_1, df_2])
df.reset_index(drop=True, inplace=True)
df.to_csv('df_activity.csv')

In [6]:
#Importing and Label Encoding 
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('df_activity.csv', index_col = 0)
label = LabelEncoder()
df['Label'] = label.fit_transform(df['Label'].values)

df_new = df.drop(['Subjects'], axis = 1)

df_s1 = df.loc[df['Subjects'] == 'Subject1']
d1_s1 = df_s1.drop(['Subjects'], axis = 1)

df_s2 = df.loc[df['Subjects'] == 'Subject2']
d2_s2 = df_s2.drop(['Subjects'], axis = 1)

window_length = 100
overlap = 60

In [7]:
#Sliding Window
def sliding_window_samples(data, samples_per_window, overlap_ratio):
    """
    Return a sliding window measured in number of samples over a data array.

    :param data: input array, can be numpy or pandas dataframe
    :param samples_per_window: window length as number of samples per window
    :param overlap_ratio: overlap is meant as percentage and should be an integer value
    :return: tuple of windows and indices
    """
    windows = []
    indices = []
    curr = 0
    win_len = samples_per_window
    if overlap_ratio is not None:
        overlapping_elements = int((overlap_ratio / 100) * (win_len))
        if overlapping_elements >= win_len:
            print('Number of overlapping elements exceeds window size.')
            return
    while curr < len(data) - win_len:
        windows.append(data[curr:curr + win_len])
        indices.append([curr, curr + win_len])
        curr = curr + win_len - overlapping_elements
    try:
        result_windows = np.array(windows)
        result_indices = np.array(indices)
    except:
        result_windows = np.empty(shape=(len(windows), win_len, data.shape[1]), dtype=object)
        result_indices = np.array(indices)
        for i in range(0, len(windows)):
            result_windows[i] = windows[i]
            result_indices[i] = indices[i]

    return result_windows, result_indices

In [8]:
#Reshaping the features and target for giving input to the model
#It takes the most common values in each window for the target after appling sliding window and 
#also returns the reshaped array. Parameters assumed f=features and t=target
def reshape(f,t):
    axis = 1
    x_new = np.reshape(f, (f.shape[0], -1))
    y, indices = np.unique(t, return_inverse=True)
    y_new = y[np.argmax(np.apply_along_axis(np.bincount, axis, indices.reshape(t.shape),None, np.max(indices) + 1), axis=axis)]
    return np.asarray(x_new), np.asarray(y_new)

**KNN Model**

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold, cross_val_score

def model_KNN(features, target, score):
    knn = KNeighborsClassifier(n_neighbors = 3,  p = 2)
    kfold = KFold(n_splits = 10, random_state=42, shuffle=True)
    scores = cross_val_score(knn, features, target, cv = kfold, scoring = score, n_jobs = -1)
    return scores.mean()

In [10]:
#Normal Cross Validation for KNN
df_1, df_2 = sliding_window_samples(df_new, window_length, overlap)
data = np.array(df_1, dtype = float)
X_data = data[:, : ,0:12]
y_data = data[:, : , 12]
X_n, y_n = reshape(X_data, y_data)
accuracy_n = model_KNN(X_n, y_n, 'accuracy')
precision_n = model_KNN(X_n, y_n, 'precision_weighted')
recall_n =  model_KNN(X_n, y_n, 'recall_weighted')
f1_n = model_KNN(X_n, y_n, 'f1_weighted')

#Per Participant Cross Validation for KNN
#Subject 1
df_sub1, df_subj_1 = sliding_window_samples(d1_s1, window_length, overlap)
data_s1 = np.array(df_sub1, dtype = float)
X_s1 = data_s1[:, : ,0:12]
y_s1 = data_s1[:, : , 12]
X_sub1, y_sub1 = reshape(X_s1, y_s1)
accuracy_s1 = model_KNN(X_sub1, y_sub1, 'accuracy')
precision_s1 = model_KNN(X_sub1, y_sub1, 'precision_weighted')
recall_s1 = model_KNN(X_sub1, y_sub1, 'recall_weighted')
f1_s1 = model_KNN(X_sub1, y_sub1, 'f1_weighted')

#Subject 2
df_sub2, df_subj_2 = sliding_window_samples(d2_s2, window_length, overlap)
data_s2 = np.array(df_sub2, dtype = float)
X_s2 = data_s2[:, : ,0:12]
y_s2 = data_s2[:, : , 12]
X_sub2, y_sub2 = reshape(X_s2, y_s2)
accuracy_s2 = model_KNN(X_sub2, y_sub2, 'accuracy')
precision_s2 = model_KNN(X_sub2, y_sub2, 'precision_weighted')
recall_s2 = model_KNN(X_sub2, y_sub2, 'recall_weighted')
f1_s2 = model_KNN(X_sub2, y_sub2, 'f1_weighted')

**LSTM model**

In [11]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, LSTM
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import f1_score, confusion_matrix
from pandas import DataFrame

def model_LSTM(X,y,k):
    scores=[]
    f1=[]
    matrix=[]
    c_matrix = 0
    split = 1
    skf = StratifiedKFold(n_splits=k,random_state=None, shuffle=False)
    for train_index, test_index in skf.split(X, y):
        #print("TRAIN:", train_index, "TEST:", test_index)
        print('Fold number : ------------- : ', split)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        #Model architecture            
        model = Sequential()
        model.add(LSTM(units=32,input_shape=[X_train.shape[1], X_train.shape[2]], activation = 'relu', return_sequences = True))
        model.add(Dropout(rate=0.1))
        model.add(Flatten())
        model.add(Dense(units=360, activation='relu'))
        model.add(Dropout(rate=0.3))
        model.add(Dense(units=6, activation='softmax'))

        #Compile the model
        model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

        #Fit data to model
        history = model.fit(X_train,y_train,epochs=10, validation_data=(X_test,y_test),verbose=1)
        y_pred = np.argmax(model.predict(X_test), axis=-1)
        
        #Genarate Metrics
        scores.append(model.evaluate(X_test,y_test))
        f1.append(f1_score(y_test, y_pred, average='weighted'))
        matrix.append(confusion_matrix(y_test, y_pred))
        split+=1        
    return np.array(scores), np.array(f1), np.array(matrix)

In [12]:
#Normal Validation
df_1, df_2 = sliding_window_samples(df_new, window_length, overlap)
data = np.array(df_1, dtype = float)

X_n = data[:, : ,0:12]
y_n = data[:, : , 12]
X_dummy, y_n = reshape(X_n, y_n)
fold_n=10
scores_n, f1_scores_n, matrix_n = model_LSTM(X_n,y_n,fold_n)
acc_scores_n = scores_n[:,-1]
c_matrix_n = matrix_n[-1]

Fold number : ------------- :  1
Epoch 1/10
115/115 [==============================] - 5s 30ms/step - loss: 0.7605 - accuracy: 0.7633 - val_loss: 0.7098 - val_accuracy: 0.8020
Epoch 2/10
115/115 [==============================] - 4s 36ms/step - loss: 0.2848 - accuracy: 0.9074 - val_loss: 0.9071 - val_accuracy: 0.7800
Epoch 3/10
115/115 [==============================] - 4s 36ms/step - loss: 0.1927 - accuracy: 0.9395 - val_loss: 0.8650 - val_accuracy: 0.8044
Epoch 4/10
115/115 [==============================] - 4s 36ms/step - loss: 0.1285 - accuracy: 0.9556 - val_loss: 0.9344 - val_accuracy: 0.7824
Epoch 5/10
115/115 [==============================] - 4s 36ms/step - loss: 0.0920 - accuracy: 0.9698 - val_loss: 1.0370 - val_accuracy: 0.8215
Epoch 6/10
115/115 [==============================] - 4s 38ms/step - loss: 0.0623 - accuracy: 0.9801 - val_loss: 1.2115 - val_accuracy: 0.7873
Epoch 7/10
115/115 [==============================] - 4s 37ms/step - loss: 0.0590 - accuracy: 0.9798 - val_lo

In [13]:
#Per Participant Cross Validation
#Subject 1
df_sub1, df_subj_1 = sliding_window_samples(d1_s1, window_length, overlap)
data_s1 = np.array(df_sub1, dtype = float)

X_s1 = data_s1[:, : ,0:12]
y_s1 = data_s1[:, : , 12]
X_dummy, y_s1 = reshape(X_s1, y_s1)
fold_s1=4
scores_s1, f1_scores_s1, matrix_s1 = model_LSTM(X_s1,y_s1,fold_s1)
acc_scores_s1 = scores_s1[:,-1]
c_matrix_s1 = matrix_s1[-1]

Fold number : ------------- :  1
Epoch 1/10
43/43 [==============================] - 3s 43ms/step - loss: 0.7285 - accuracy: 0.7469 - val_loss: 0.5761 - val_accuracy: 0.8070
Epoch 2/10
43/43 [==============================] - 2s 38ms/step - loss: 0.2398 - accuracy: 0.9100 - val_loss: 0.4887 - val_accuracy: 0.8706
Epoch 3/10
43/43 [==============================] - 2s 41ms/step - loss: 0.1248 - accuracy: 0.9510 - val_loss: 0.5238 - val_accuracy: 0.8750
Epoch 4/10
43/43 [==============================] - 2s 41ms/step - loss: 0.0583 - accuracy: 0.9817 - val_loss: 0.7327 - val_accuracy: 0.8377
Epoch 5/10
43/43 [==============================] - 2s 50ms/step - loss: 0.0356 - accuracy: 0.9898 - val_loss: 0.8988 - val_accuracy: 0.8465
Epoch 6/10
43/43 [==============================] - 2s 47ms/step - loss: 0.0252 - accuracy: 0.9920 - val_loss: 0.9098 - val_accuracy: 0.8443
Epoch 7/10
43/43 [==============================] - 2s 40ms/step - loss: 0.0346 - accuracy: 0.9898 - val_loss: 0.9358 - v

In [14]:
#Subject 2
df_sub2, df_subj_2 = sliding_window_samples(d2_s2, window_length, overlap)
data_s2 = np.array(df_sub2, dtype = float)

X_s2 = data_s2[:, : ,0:12]
y_s2 = data_s2[:, : , 12]
X_dummy, y_s2 = reshape(X_s2, y_s2)
fold_s2=8
scores_s2, f1_scores_s2, matrix_s2  = model_LSTM(X_s2,y_s2,fold_s2)
acc_scores_s2 = scores_s2[:,-1]
c_matrix_s2 = matrix_s2[-1]

Fold number : ------------- :  1
Epoch 1/10
62/62 [==============================] - 3s 34ms/step - loss: 0.7723 - accuracy: 0.7462 - val_loss: 1.0068 - val_accuracy: 0.7314
Epoch 2/10
62/62 [==============================] - 2s 32ms/step - loss: 0.2404 - accuracy: 0.9260 - val_loss: 1.0734 - val_accuracy: 0.7633
Epoch 3/10
62/62 [==============================] - 2s 31ms/step - loss: 0.3661 - accuracy: 0.9438 - val_loss: 1.3280 - val_accuracy: 0.7633
Epoch 4/10
62/62 [==============================] - 2s 33ms/step - loss: 0.2525 - accuracy: 0.9397 - val_loss: 1.1224 - val_accuracy: 0.7279
Epoch 5/10
62/62 [==============================] - 2s 35ms/step - loss: 0.1032 - accuracy: 0.9681 - val_loss: 1.1303 - val_accuracy: 0.7774
Epoch 6/10
62/62 [==============================] - 2s 36ms/step - loss: 0.0752 - accuracy: 0.9787 - val_loss: 1.1761 - val_accuracy: 0.7703
Epoch 7/10
62/62 [==============================] - 2s 37ms/step - loss: 0.0440 - accuracy: 0.9868 - val_loss: 1.3005 - v

In [15]:
print('Normal Cross Validation, Model : KNN')
print('Mean_accuracy: %.3f' % accuracy_n)
print('Mean_precision_score: %.3f' % precision_n)
print('Mean_recall_score: %.3f' % recall_n)
print('Mean_F1_score: %.3f' % f1_n)

print('\nSUB 1 Cross Validation, Model : KNN')
print('Mean_accuracy_s1: %.3f' % accuracy_s1)
print('Mean_precision_score_s1: %.3f' % precision_s1)
print('Mean_recall_score_s1: %.3f' % recall_s1)
print('Mean_F1_score_s1: %.3f' % f1_s1)

print('\nSUB 2 Cross Validation, Model : KNN')
print('Mean_accuracy_s2: %.3f' % accuracy_s2)
print('Mean_precision_score_s2: %.3f' % precision_s2)
print('Mean_recall_score_s2: %.3f' % recall_s2)
print('Mean_F1_score_s2: %.3f' % f1_s2)

print('\nNormal Cross Validation, Model : LSTM')
print('Accuracy : %0.4f' %acc_scores_n.mean())
print('F1_score : %0.4f' %f1_scores_n.mean())
print('Confusion_matrix : Null, dribbling, layup, running, shooting, walking\n', c_matrix_n)

print('\nSUB 1 Cross Validation, Model : LSTM')
print('Accuracy : %0.4f' %acc_scores_s1.mean())
print('F1_score : %0.4f' %f1_scores_s1.mean())
print('Confusion_matrix : Null, layup, running, shooting, walking \n', c_matrix_s1)

print('\nSUB 2 Cross Validation, Model : LSTM')
print('Accuracy : %0.4f' %acc_scores_s2.mean())
print('F1_score : %0.4f' %f1_scores_s2.mean())
print('Confusion_matrix : Null, dribbling, layup, running, shooting, walking \n', c_matrix_s2)

Normal Cross Validation, Model : KNN
Mean_accuracy: 0.726
Mean_precision_score: 0.787
Mean_recall_score: 0.726
Mean_F1_score: 0.703

SUB 1 Cross Validation, Model : KNN
Mean_accuracy_s1: 0.753
Mean_precision_score_s1: 0.811
Mean_recall_score_s1: 0.753
Mean_F1_score_s1: 0.738

SUB 2 Cross Validation, Model : KNN
Mean_accuracy_s2: 0.754
Mean_precision_score_s2: 0.798
Mean_recall_score_s2: 0.754
Mean_F1_score_s2: 0.715

Normal Cross Validation, Model : LSTM
Accuracy : 0.8802
F1_score : 0.8792
Confusion_matrix : Null, dribbling, layup, running, shooting, walking
 [[84  1  0  2  0  1]
 [ 7 30  9  0  0  0]
 [ 0  2 68  2  0  2]
 [ 9  0  3 49  0  0]
 [ 2  1 11  0 42  8]
 [ 0  0  5  3  1 66]]

SUB 1 Cross Validation, Model : LSTM
Accuracy : 0.8908
F1_score : 0.8890
Confusion_matrix : Null, layup, running, shooting, walking 
 [[95  8  1  6  5]
 [ 4 78  2  0  0]
 [ 4 18 46  0  6]
 [ 6  5  0 73  5]
 [ 1  2 11  0 79]]

SUB 2 Cross Validation, Model : LSTM
Accuracy : 0.8813
F1_score : 0.8805
Confusi